from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from app.database import get_db
from app.models.clinic import Clinic
from app.models.user import UserRole
from app.schemas.clinic import ClinicCreate, ClinicUpdate, ClinicResponse
from app.routers.auth import get_current_active_user
from app.models.user import User
import firebase_admin
from firebase_admin import credentials, firestore
import os

router = APIRouter(prefix="/clinics", tags=["clinics"])

# Initialize Firebase Admin SDK for Firestore
def initialize_firebase_firestore():
    """Initialize Firebase Admin SDK to connect to Firestore"""
    try:
        # Check if already initialized
        if not firebase_admin._apps:
            # Use the same Firebase credentials as notifications
            cred_path = "firebase-credentials.json"
            if os.path.exists(cred_path):
                cred = credentials.Certificate(cred_path)
                firebase_admin.initialize_app(cred)
                print("✅ Firebase Firestore initialized successfully")
                return True
            else:
                print(f"⚠️ Firebase credentials file not found: {cred_path}")
                return False
        return True
    except Exception as e:
        print(f"❌ Error initializing Firebase Firestore: {e}")
        return False

def get_clinics_from_firestore() -> List[dict]:
    """Fetch clinics from Firebase Firestore"""
    try:
        if not initialize_firebase_firestore():
            print("Firebase not initialized, returning empty list")
            return []
        
        db = firestore.client()
        clinics_ref = db.collection('clinics')
        docs = clinics_ref.stream()
        
        clinics_list = []
        for doc in docs:
            clinic_data = doc.to_dict()
            clinic_data['id'] = doc.id
            clinics_list.append(clinic_data)
        
        print(f"✅ Fetched {len(clinics_list)} clinics from Firebase Firestore")
        return clinics_list
    except Exception as e:
        print(f"❌ Error fetching clinics from Firestore: {e}")
        return []

@router.get("/", response_model=List[ClinicResponse])
async def get_clinics(
    db: Session = Depends(get_db)
    # Removed authentication requirement to allow signup to fetch clinics
):
    """Get all clinics from Firebase Firestore"""
    try:
        # Fetch clinics from Firebase Firestore
        firebase_clinics = get_clinics_from_firestore()
        
        if not firebase_clinics:
            print("⚠️ No clinics found in Firebase, checking database...")
            # Fallback to database if Firebase has no clinics
            clinics = db.query(Clinic).all()
            return clinics
        
        # Sync Firebase clinics to database
        synced_count = 0
        for clinic_data in firebase_clinics:
            # Check if clinic exists in database
            existing_clinic = db.query(Clinic).filter(Clinic.id == clinic_data['id']).first()
            
            if existing_clinic:
                # Update existing clinic
                for key, value in clinic_data.items():
                    if key != 'id' and hasattr(existing_clinic, key):
                        setattr(existing_clinic, key, value)
            else:
                # Create new clinic from Firebase
                # Filter out id since it's auto-generated by SQLAlchemy
                clean_clinic_data = {k: v for k, v in clinic_data.items() if k != 'id'}
                clinic = Clinic(**clean_clinic_data)
                clinic.id = clinic_data['id']
                db.add(clinic)
                synced_count += 1
        
        db.commit()
        
        if synced_count > 0:
            print(f"✅ Synced {synced_count} new clinics from Firebase to database")
        
        # Return all clinics from database
        clinics = db.query(Clinic).all()
        print(f"✅ Returning {len(clinics)} clinics from database")
        return clinics
        
    except Exception as e:
        print(f"❌ Error in get_clinics: {e}")
        # Fallback to database query
        clinics = db.query(Clinic).all()
        return clinics

@router.get("/user")
async def get_clinics_by_user(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Get all clinics associated with the current user"""
    # For doctors and hospital admins, return clinics they are associated with
    clinics = []
    
    if str(current_user.role) in [str(UserRole.DOCTOR), str(UserRole.HOSPITAL_ADMIN)]:
        # If user has associated clinics via the many-to-many relationship, get those
        # Since we haven't fully implemented the many-to-many relationship yet, 
        # we'll return the primary clinic for now and associated clinics if available
        if hasattr(current_user, 'associated_clinics') and current_user.associated_clinics:
            # If the user has associated clinics through the relationship
            clinics = current_user.associated_clinics
        elif current_user.clinic_id is not None:
            # Otherwise, get the primary clinic
            clinic = db.query(Clinic).filter(Clinic.id == current_user.clinic_id).first()
            if clinic:
                clinics = [clinic]
        else:
            # If no clinic is associated, return empty list
            clinics = []
    elif str(current_user.role) == str(UserRole.ADMIN):
        # Admins can see all clinics
        clinics = db.query(Clinic).all()
    else:
        # Regular users get their associated clinic
        if current_user.clinic_id is not None:
            clinic = db.query(Clinic).filter(Clinic.id == current_user.clinic_id).first()
            if clinic:
                clinics = [clinic]
    
    return clinics

@router.get("/{clinic_id}")
async def get_clinic_by_id(
    clinic_id: str,
    db: Session = Depends(get_db)
):
    """Get a specific clinic by ID"""
    clinic = db.query(Clinic).filter(Clinic.id == clinic_id).first()
    
    if not clinic:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Clinic not found"
        )
    
    return clinic
